# version: 1.1.0
# modified: 2026-02-21

openai-api-base: https://openrouter.ai/api/v1

# Alternatives
#
model: openrouter/minimax/minimax-m2.5
model-settings-file: .aider.minimax-m2.5.yml
#model: openrouter/z-ai/glm-5
#model-settings-file: .aider.glm-5.yml
#model: openrouter/google/gemini-3-flash-preview
#model-settings-file: .aider.gemini-3-flash.yml
#model: openrouter/google/gemini-3.1-pro-preview
#model-settings-file: .aider.gemini-3.1-pro.yml
