- name: openrouter/google/gemini-3-flash-preview
  edit_format: diff # Format for code edits (diff is efficient for programming tasks; Gemini 3 Flash handles it well)
  use_repo_map: true # Provides project structure context to the model
  use_temperature: false # Disables randomness for more deterministic reasoning outputs (ideal for this thinking model)
  streaming: true # Enables real-time token-by-token responses
  extra_params: # Provider-specific options passed to the API
    max_tokens: 32768 # Matches Gemini 3 Flash Preview's high output capacity; adjust if you hit limits (context is 1M tokens)
    top_p: 0.95 # Controls output diversity
  accepts_settings: # Enables advanced reasoning controls (this model excels at configurable thinking)
    - thinking_tokens # Allows specifying tokens for internal thinking steps
    - reasoning_effort # Supports effort levels like 'minimal', 'low', 'medium', 'high' for agentic/coding workflows
  reasoning_tag: think # Wraps reasoning steps in <think> tags for structured output
