openai-api-base: https://openrouter.ai/api/v1
openai-api-key: SECRET
model: openrouter/z-ai/glm-5
model-settings-file: .aider.model.settings.yml  # Optional: Points to your custom model settings file
